VacationDays/Controllers/Example/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using VacationDays.Models;
using VacationDays.Services;

namespace VacationDays.Controllers
{
    /// <summary>
    /// This class is used for learning / testing only
    /// </summary>

    public class UserController : Controller
    {
        private IVacationData _vacationData;
        private IUserInfo _userInfo;
        private UserManager<IdentityUser> _userManager;

        public UserController(IVacationData vacationData, IUserInfo userInfo, UserManager<IdentityUser> userManager)
        {
            _vacationData = vacationData;
            _userInfo = userInfo;
            _userManager = userManager; 
        }

        public IActionResult Index()
        {

            return Content(User.Identity.Name);
        }

        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> Roles()
        {
            var user = await GetCurrentUserAsync();
            var roles = await _userManager.GetRolesAsync(user);

            string rolesString = "";
            foreach (string role in roles)
                rolesString += " " + role;


            if (_userInfo.IsAuthenticated())
                return Content(rolesString);               
            else
                return Redirect("/Identity/Account/Register");  
        }

        public async Task<IActionResult> Claims()
        {
            var user = await GetCurrentUserAsync();
            var roles = await _userManager.GetRolesAsync(user);

            string rolesString = "";

            foreach (Claim role in User.Claims)
                rolesString += " " + role.ToString();

            if (_userInfo.IsAuthenticated())
                return Content(rolesString);
            //return Content(_userInfo.GetUserID() + " has admin role: " + User.IsInRole("Manager"));
            else
                return Redirect("/Identity/Account/Register");
        }

    }
}

VacationDays/Controllers/NationalFreeDaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VacationDays.Models;
using VacationDays.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace VacationDays.Controllers
{
    [Authorize (Roles = "Manager,Admin")]
    public class NationalFreeDaysController : Controller
    {
        private INationalFreeDaysData _nationalFreeDaysData;

        public NationalFreeDaysController(INationalFreeDaysData nationalFreeDaysData)
        {
            _nationalFreeDaysData = nationalFreeDaysData;

        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _nationalFreeDaysData.GetAll();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  // pretty good practice for POST functions
        public IActionResult AddFreeDay(NationalFreeDay freeDay)
        {
            //return Content(freeDay.Date.ToShortDateString()); 

            List<string> errors = new List<string>();

            if (freeDay==null)
            {
                string nullInput = "Input cannot be null!";
                errors.Add(nullInput);
                return View("AddFreeDayError", errors);
            }

            if (_nationalFreeDaysData.IsNationalFreeDay(freeDay.Date))
            {
                string errorItemAlreadyExists = "The selected date already exists!";
                errors.Add(errorItemAlreadyExists);
            }

            if (freeDay.Date == DateTime.MinValue)
            {
                string errorChangeDefaultValue = "Please set a date value.";
                errors.Add(errorChangeDefaultValue); 
            }

            if (ModelState.IsValid && errors.Count == 0)
            {
                _nationalFreeDaysData.Add(freeDay);
                // After POSTing, its good practice to RE-DIRECT to something, so it wont POST again on a page refresh.
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("AddFreeDayError",errors);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  // pretty good practice for POST functions
        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                var dayToDelete = _nationalFreeDaysData.Get(id);

                if (dayToDelete == null)
                {
                    return NotFound();
                }

                _nationalFreeDaysData.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            else
                return BadRequest();            
        }


    }
}

VacationDays/Controllers/VacationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VacationDays.Classes;
using VacationDays.Models;
using VacationDays.Services;
using VacationDays.ViewModels;
using VacationDays.ViewModels.Vacations;

namespace VacationDays.Controllers
{
    [Authorize]
    public class VacationController : Controller
    {
        private DateHelper _dateHelper;
        private IVacationData _vacationData;
        private IUserInfo _userInfo;
        private INationalFreeDaysData _nationalFreeDaysData;
        private IUserFreeDaysInfoData _userFreeDaysInfoData;

        public VacationController(IVacationData vacationData, IUserInfo userInfo, INationalFreeDaysData nationalFreeDaysData,
            DateHelper dateHelper, IUserFreeDaysInfoData userFreeDaysInfoData)
        {
            _dateHelper = dateHelper;
            _vacationData = vacationData;
            _userInfo = userInfo;
            _nationalFreeDaysData = nationalFreeDaysData;
            _userFreeDaysInfoData = userFreeDaysInfoData;
        }

        public IActionResult Index()
        {
            var model = _vacationData.GetAll(_userInfo); 
            return View(model); 
        }

        public IActionResult Details(int id)
        {
            var model = _vacationData.Get(id);

            if (model != null)
                return View(model);
            else 
                return NotFound("Vacation is not found!!!"); 
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  // pretty good practice for POST functions
        public IActionResult Create(VacationDateTimeEditModel model)
        {
            List<string> errors = CheckVacationCreationForErrors(model);

            if (ModelState.IsValid && errors.Count == 0 && model != null)
            {
                var newVacation = new Vacation();
                newVacation.Status = VacationStatus.Pending;
                newVacation.OwnerId = _userInfo.GetUserID(); 
                newVacation.StartDate = model.StartDate;
                newVacation.EndDate = model.EndDate;
                newVacation.DaysTaken = _dateHelper.GetWorkingDays(newVacation.StartDate, newVacation.EndDate);
                newVacation = _vacationData.Add(newVacation);

                // After POSTing, its good practice to RE-DIRECT to something, so it wont POST again on a page refresh.
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("CreateError", errors);
            }
        }

        List<string> CheckVacationCreationForErrors(VacationDateTimeEditModel model)
        {
            List<string> errors = new List<string>();

            if (model == null)
            {
                string nullModel = "Model cannot be null";
                errors.Add(nullModel);
                return errors;
            }

            int daysTaken = _dateHelper.GetWorkingDays(model.StartDate, model.EndDate);

            if (model.EndDate >= model.StartDate && daysTaken == 0)
            {
                string errorZeroDays = "No working day was selected";
                errors.Add(errorZeroDays);                
            }

            if (model.EndDate < model.StartDate)
            {
                string errorNegativeDays = "Vacation cannot end before it starts.";
                errors.Add(errorNegativeDays);
            }

            return errors;
        }

        public IActionResult ShowFreeDays()
        {
            var vacationData = _vacationData.GetAll(_userInfo).Where(v => v.Status == VacationStatus.Approved).OrderBy(v => v.EndDate);

            var model = new MyFreeDaysViewModel();
            model.YearlyHistory = new SortedDictionary<int, int>();

            foreach (Vacation v in vacationData)
            {
                for (var date = v.StartDate; date <= v.EndDate; date = date.AddDays(1))
                {
                    if (_dateHelper.IsWorkingDay(date))
                    {
                        if (model.YearlyHistory.ContainsKey(date.Year))
                        {
                            model.YearlyHistory[date.Year] += 1;
                        }
                        else
                        {
                            model.YearlyHistory.Add(date.Year, 1);
                        }
                    }
                }
            }
            
            var userFreeDaysInfo = _userFreeDaysInfoData.GetByUserID(_userInfo.GetUserID());

            // if the user has no data, just create a default user free days info. This should never happen on the live app.
            // a userFreeDaysInfo should be created and saved in DB for each user when the user account is created. 
            if (userFreeDaysInfo == null)
            {
                userFreeDaysInfo = _userFreeDaysInfoData.Add(_userInfo.GetUserID(), 25, 1, DateTime.Now);
            }

            model.DateHired = userFreeDaysInfo.JoinedCompanyDate;
            model.FreeDaysRequiredByLaw = userFreeDaysInfo.FreeDaysRequiredByLaw;
            model.BonusDaysFromCompany = userFreeDaysInfo.FreeDaysAsBonusFromCompany;
            model.FreeDaysGivenThisYear = _userFreeDaysInfoData.GetFreeDaysGivenForYear(_userInfo.GetUserID(), DateTime.Now.Year);
           
            int daysTakenThisYear;
            model.YearlyHistory.TryGetValue(DateTime.Now.Year, out daysTakenThisYear);
            model.VacationDaysTakenThisYear = daysTakenThisYear;

            int daysTakenLastYear;
            model.YearlyHistory.TryGetValue(DateTime.Now.Year-1, out daysTakenLastYear);
            model.FreeDaysLeftFromLastYear = _userFreeDaysInfoData.GetFreeDaysGivenForYear(_userInfo.GetUserID(), DateTime.Now.Year - 1) - daysTakenLastYear;

            model.TotalAvailableFreeDays = model.FreeDaysGivenThisYear + model.FreeDaysLeftFromLastYear - daysTakenThisYear;

            return View("MyFreeDays", model);
        }

    }
}

VacationDays/Controllers/VacationsManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using VacationDays.Classes;
using VacationDays.Models;
using VacationDays.Services;
using VacationDays.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace VacationDays.Controllers
{
    [Authorize(Roles = "Manager")]
    public class VacationsManagementController : Controller
    {
        private DateHelper _dateHelper;
        private IVacationData _vacationData;
        private IUserInfo _userInfo;
        private UserManager<IdentityUser> _userManager;
        private IEmailService _emailService;

        const string MAIL_EXPEDITOR = "andreilng41@gmail.com";
        const string CONFIRMATON_EMAIL_TITLE = "Vacation request approved";
        const string CONFIRMATON_EMAIL_BODY = "Your vacation has been approved by your manager.";
        const string REJECTION_EMAIL_TITLE = "Vacation request denied";
        const string REJECTION_EMAIL_BODY = "Your vacation request has been denied. Please contact your manager.";
        const string START_DATE = "Start date: ";
        const string END_DATE =   "End date:   ";
        const string WORKING_DAYS = "Working days: ";
        const string NEW_LINE = "\n";

        public VacationsManagementController(IVacationData vacationData, IUserInfo userInfo, UserManager<IdentityUser> userManager,
            DateHelper dateHelper, IEmailService emailService)
        {
            _dateHelper = dateHelper;
            _vacationData = vacationData;
            _userInfo = userInfo;
            _userManager = userManager;
            _emailService = emailService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var vmo = new VacationManagementOutputModel();

            foreach (Vacation vacation in _vacationData.GetAll())
            {
                var vacationPresentation = new VacationPresentation();
                vacationPresentation.Id = vacation.Id;
                vacationPresentation.Status = vacation.Status;
                vacationPresentation.StartDate = vacation.StartDate;
                vacationPresentation.EndDate = vacation.EndDate;
                vacationPresentation.DaysTaken = vacation.DaysTaken;
                vacationPresentation.OwnerName = _userManager.Users.FirstOrDefault(user => user.Id == vacation.OwnerId).UserName;
                vmo.vacationsList.Add(vacationPresentation); 
            }

            return View(vmo);
        }       

        public IActionResult Pending()
        {
            var vmo = new VacationManagementOutputModel();

            foreach (Vacation vacation in _vacationData.GetAll().Where(r=> r.Status == VacationStatus.Pending))
            {
                var vacationPresentation = new VacationPresentation();
                vacationPresentation.Id = vacation.Id;
                vacationPresentation.Status = vacation.Status;
                vacationPresentation.StartDate = vacation.StartDate;
                vacationPresentation.EndDate = vacation.EndDate;
                vacationPresentation.DaysTaken = vacation.DaysTaken;
                vacationPresentation.OwnerName = _userManager.Users.First(user => user.Id == vacation.OwnerId).UserName;
                vmo.vacationsList.Add(vacationPresentation);
            }

            return View(vmo);
        }

        public IActionResult Details(int id)
        {
            var model = _vacationData.Get(id);

            if (model != null)
                return View("Details",model);
            else
                return NotFound("Vacation is not found!");
        }

        // !! set the param names to model fields names! otherwise it wont bind!
        public async Task<IActionResult> Approve(int id, bool sendEmail, string test)
        {             
            _vacationData.Approve(id);
            await SendEmail(id, CONFIRMATON_EMAIL_TITLE, CONFIRMATON_EMAIL_BODY);
            return RedirectToAction(nameof(Pending)); 
        }

        public async Task<IActionResult> Reject(int id, bool sendEmail)
        {
            _vacationData.Reject(id);
            await SendEmail(id, REJECTION_EMAIL_TITLE, REJECTION_EMAIL_BODY);
            return RedirectToAction(nameof(Pending));
        }

        public async Task<IActionResult> SendEmail(int id, string title, string content)
        {          
            string ownerId = _vacationData.Get(id).OwnerId;
            string targetEmail = _userManager.Users.First(user => user.Id == ownerId).Email;
          
            using (var smtpClient = HttpContext.RequestServices.GetRequiredService<SmtpClient>())
            {
                smtpClient.EnableSsl = true;
                smtpClient.TargetName = "STARTTLS/smtp.gmail.com";
                await smtpClient.SendMailAsync(new MailMessage(
                       from: MAIL_EXPEDITOR,
                       to: targetEmail,
                       subject: title,
                       body: BuildEmailContent(id, content)
                       ));

                return RedirectToAction(nameof(Pending));
            }
        }

        private string BuildEmailContent(int id, string bodyContent)
        {
            string content = bodyContent; 
            content += NEW_LINE;
            string sd = START_DATE + _vacationData.Get(id).StartDate.ToString("MMMM, dd, yyyy");
            content += sd;
            content += NEW_LINE;
            string ed = END_DATE + _vacationData.Get(id).EndDate.ToString("MMMM, dd, yyyy");
            content += ed;
            content += NEW_LINE;
            content += WORKING_DAYS + _dateHelper.GetWorkingDays(_vacationData.Get(id).StartDate, _vacationData.Get(id).EndDate);
            return content; 
        }

      
    }
}

VacationDays/Views/Shared/Details.cshtml
@model VacationDays.Models.Vacation

<h1> @Model.Id</h1>

<div>
    Period: <br />
    @Model.StartDate.ToShortDateString()<br />
    @Model.EndDate.ToShortDateString()<br />
    <a asp-action="Index" asp-controller="Vacation">Back</a>
</div>

VacationDays/Views/Shared/_Layout - Original.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VacationDays</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Vacation Days</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                    <li><a asp-area="" asp-controller="Vacation" asp-action="Index">Vacations</a></li>
                    <li><a asp-area="" asp-controller="Vacation" asp-action="ShowFreeDays">My Free Days</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="Roles">Test user roles</a></li>
                    }

                    @if (User.IsInRole("Manager"))
                    {
                        <li><a asp-area="" asp-controller="VacationsManagement" asp-action="Index">Management</a></li>
                    }

                    @if (User.IsInRole("Manager"))
                    {
                        <li><a asp-area="" asp-controller="NationalFreeDays" asp-action="Index">National Free Days</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - VacationDays</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

VacationDays/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VacationDays</title>
    <link rel="stylesheet" type="text/css" href="~/css/Layout.css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    

    <partial name="_CookieConsentPartial" />

    <partial name="_SidebarPartial" />

    <div class="container body-content">
        <div class="roundedBodyContent">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - VacationDays</p>
            </footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

VacationDays/Views/Shared/_SidebarPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject VacationDays.Services.NotificationsService Notifications; 
 
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/css/Sidebar.css">
    <link rel="stylesheet" type="text/css" href="~/css/Switches.css">
</head>
<body>

    <div class="sidenavBackground"></div>

    <div class="sidenav">
        @if (SignInManager.IsSignedIn(User))
        {
            <span class="sidenavText" style="color:white">Hello,</span>
            <a class="name" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@UserManager.GetUserName(User)</a>
            <br />
            <a class="sidenavButton" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Account settings</a>
            <a class="sidenavButton" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })"> Logout</a>

        }
        else
        {
            <a class="sidenavButton" asp-area="Identity" asp-page="/Account/Register">Register</a>
            <a class="sidenavButton" asp-area="Identity" asp-page="/Account/Login">Login</a>
        }


        <div style="opacity:0.5">
            <hr class="style-two">
        </div>

        <a class="sidenavButton" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

        @if (SignInManager.IsSignedIn(User))
        {
            <div style="opacity:0.5">
                <hr class="style-two">
            </div>
            <a class="sidenavButton" asp-area="" asp-controller="Vacation" asp-action="Create">New vacation request</a>
            <a class="sidenavButton" asp-area="" asp-controller="Vacation" asp-action="Index">My requests</a>
            <a class="sidenavButton" asp-area="" asp-controller="Vacation" asp-action="ShowFreeDays">My Free Days</a>
        }

        @if (User.IsInRole("Manager"))
        {
            <div style="opacity:0.5">
                <hr class="style-two">
            </div>



            <a class="sidenavButton" asp-area="" asp-controller="VacationsManagement" asp-action="Pending">
                Pending requests
                @if (@Notifications.PendingRequestsNotification.GetValue() > 0)
                {
                    <span class="notificationOrange"> @Notifications.PendingRequestsNotification.GetValue()</span>
                }
            </a>

            <a class="sidenavButton" asp-area="" asp-controller="VacationsManagement" asp-action="Index">Request history</a>
            <a class="sidenavButton" asp-area="" asp-controller="NationalFreeDays" asp-action="Index">National Free Days</a>
        }

        @if (User.IsInRole("Admin"))
        {
            <div style="opacity:0.5">
                <hr class="style-two">
            </div>
            <a class="sidenavButton" asp-area="" asp-controller="User" asp-action="Roles" style="color:white">Test user roles</a>
        }

        <div style="opacity:0.5">
            <hr class="style-two">
        </div>

        @*<button class="accordion"><span class="accordionText">About the web app </span><span id="plus" class="plus"></span></button>*@
        <button class="accordion"><span class="accordionText">About the web app </span>
                                  <span id="plus" class="plus"><img id="img" src="~/plus.png"class="plusImg"><span></span>
            </button> 

        <div class="panel"> 

            <a class="sidenavButton" asp-area="" asp-controller="Home" asp-action="About">About</a>
            <a class="sidenavButton" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            <a class="sidenavButton" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

        <div style="opacity:0.5">
            <hr class="style-two">
        </div>     
     
    </div>
    <br />

    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;
        var img = document.getElementById("img");

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.maxHeight) {
                    panel.style.maxHeight = null;
                    plus.style.transform = "rotate(0deg)";
                    img.src = "../plus.png";
                }
                else {
                    panel.style.maxHeight = panel.scrollHeight + "px";
                    plus.style.transform = "rotate(720deg)";
                    img.src = "../minus.png";
                }
            });
        }
    </script>
     
</body>
</html>